### ISSUE TITLE
Error on build: ignoring attributes on template argument

### ISSUE THREAD

**Issue by TheSunCat** [bkryza/clang-uml#244] opened 2024-02-24 14:11 UTC
Hi! I'm trying to build clang-uml on Arch (clang 16.0.6) and it's failing with this error:
```cpp
/home/apm/Downloads/clang-uml/src/util/util.cc: In function ‘std::string clanguml::util::get_process_output(const std::string&)’:
/home/apm/Downloads/clang-uml/src/util/util.cc:38:44: error: ignoring attributes on template argument ‘int (*)(FILE*)’ [-Werror=ignored-attributes]
   38 |     std::unique_ptr<FILE, decltype(&pclose)> pipe(
      |                                            ^
cc1plus: all warnings being treated as errors
make[3]: *** [src/CMakeFiles/clang-umllib.dir/build.make:1070: src/CMakeFiles/clang-umllib.dir/util/util.cc.o] Error 1
```

I simply cloned it and ran `make release` as instructed [here](https://github.com/bkryza/clang-uml/blob/master/docs/installation.md#linux).

**Comment by bkryza** [comment] 2024-02-24 14:32
@TheSunCat I've just checked on my Arch setup and it builds fine - can you post the beginning of the cmake output after `make release` in particular:

```console
❯ make release
cmake -S . -B release \
	-G"Unix Makefiles" \
	-DGIT_VERSION=0.5.0-10-ga404a30 \
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_CXX_FLAGS="" \
	-DCMAKE_EXE_LINKER_FLAGS="" \
	-DLLVM_VERSION= \
	-DLLVM_CONFIG_PATH= \
	-DLINK_LLVM_SHARED=ON \
	-DCMAKE_PREFIX= \
	-DENABLE_CXX_MODULES_TEST_CASES=OFF
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib/ccache/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib/ccache/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.43.0") 
-- clang-uml version: 0.5.0-10-ga404a30
-- Checking for LLVM and Clang...
-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/libtinfo.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.3.1")  
-- Found zstd: /usr/lib/libzstd.so  
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.12.4") 
-- Linker detection: GNU ld
-- Found LLVM 16.0.6
-- Using LLVMConfig.cmake from: /usr/lib/cmake/llvm
-- LLVM library dir: /usr/lib
-- Found LibTooling libraries: clang-cpp;LLVM
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Checking for yaml-cpp...
-- Found yaml-cpp libraries: yaml-cpp
-- Enabling C++20 test cases
-- Configuring done (1.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/bartek/devel/clang-uml/release
```

Anyway, the error is due to the fact that I use function pointer to `pclose` system call as deleter for the `std::unique_ptr`, and apparently on your system the `pclose` system call has some attributes attached to it, in my case it's simply (in stdio.h): 

```c
extern int pclose (FILE *__stream);
```

I will try to refactor this to use a custom deleter class instead of a function pointer which should solve the problem.

For now you can try to add the following compile flag to `CMakeLists.txt` CUSTOM_COMPILE_OPTIONS:

```
set(CUSTOM_COMPILE_OPTIONS ${CUSTOM_COMPILE_OPTIONS} -Wno-ignored-attributes)
```
somewhere after line 87...

**Comment by TheSunCat** [comment] 2024-02-24 18:04
Sure! Here's the cmake output:

```cpp
cmake -S . -B release \
	-G"Unix Makefiles" \
	-DGIT_VERSION=0.5.0-10-ga404a30 \
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_CXX_FLAGS="" \
	-DCMAKE_EXE_LINKER_FLAGS="" \
	-DLLVM_VERSION= \
	-DLLVM_CONFIG_PATH= \
	-DLINK_LLVM_SHARED=ON \
	-DCMAKE_PREFIX= \
	-DENABLE_CXX_MODULES_TEST_CASES=OFF
-- clang-uml version: 0.5.0-10-ga404a30
-- Checking for LLVM and Clang...
-- Found LLVM 16.0.6
-- Using LLVMConfig.cmake from: /usr/lib/cmake/llvm
-- LLVM library dir: /usr/lib
-- Found LibTooling libraries: clang-cpp;LLVM
-- Checking for yaml-cpp...
-- Found yaml-cpp libraries: yaml-cpp
-- Enabling C++20 test cases
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /home/apm/Downloads/clang-uml/release
```

Disabling that warning indeed allows it to build!

**Comment by bkryza** [comment] 2024-02-24 18:39
@TheSunCat Ok, great it helped. Unfortunately I forgot to mention to run `make clean` before rebuilding - because the compiler is already cached by cmake. If possible could you run this again like this:

```console
make clean
make release
```
and paste the CMake output?

The thing is that this issue is probably related to the compiler version you have and I'd like to know which one it is so I can reproduce it and fix it properly.

Anyway, if this is some latest GCC warning elevated to error, it seems a lot more people will be inconvenienced by it: https://github.com/search?type=code&q=decltype%28%26pclose%29   ;-)

**Comment by TheSunCat** [comment] 2024-02-24 21:02
Aha, it's using my system GCC over clang! Here's the output:
```cpp
cmake -S . -B release \
	-G"Unix Makefiles" \
	-DGIT_VERSION=0.5.0-10-ga404a30 \
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_CXX_FLAGS="" \
	-DCMAKE_EXE_LINKER_FLAGS="" \
	-DLLVM_VERSION= \
	-DLLVM_CONFIG_PATH= \
	-DLINK_LLVM_SHARED=ON \
	-DCMAKE_PREFIX= \
	-DENABLE_CXX_MODULES_TEST_CASES=OFF
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.44.0") 
-- clang-uml version: 0.5.0-10-ga404a30
-- Checking for LLVM and Clang...
-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /usr/lib/libtinfo.so  
-- Found ZLIB: /usr/lib/libz.so (found version "1.3.1")  
-- Found zstd: /usr/lib/libzstd.so  
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.12.5") 
-- Linker detection: GNU ld
-- Found LLVM 16.0.6
-- Using LLVMConfig.cmake from: /usr/lib/cmake/llvm
-- LLVM library dir: /usr/lib
-- Found LibTooling libraries: clang-cpp;LLVM
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Checking for yaml-cpp...
-- Found yaml-cpp libraries: yaml-cpp
-- Enabling C++20 test cases
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /home/apm/Downloads/clang-uml/release
```

The output of `paru -Qi gcc` to get info about the GCC package on my system:
```
Name            : gcc
Version         : 13.2.1-5
Description     : The GNU Compiler Collection - C and C++ frontends
Architecture    : x86_64
URL             : https://gcc.gnu.org
Licenses        : GPL-3.0-with-GCC-exception  GFDL-1.3-or-later
Groups          : None
Provides        : gcc-multilib
Depends On      : gcc-libs=13.2.1-5  binutils>=2.28  libmpc  zstd  libisl.so=23-64
Optional Deps   : lib32-gcc-libs: for generating code for 32-bit ABI [installed]
Required By     : base-devel  cbonsai  clang  clang15  dkms  gcc-fortran  nim  vala
Optional For    : xorg-xrdb
Conflicts With  : None
Replaces        : gcc-multilib
Installed Size  : 184.18 MiB
Packager        : Frederik Schwan <freswa@archlinux.org>
Build Date      : Fri 02 Feb 2024 11:36:00
Install Date    : Sun 04 Feb 2024 23:35:40
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Comment by bkryza** [comment] 2024-02-24 21:26
@TheSunCat Thanks for the feedback!

There is no problem with compiling `clang-uml` with GCC, it only needs to be linked to Clang. I actually build it with GCC myself as it is still default compiler on most Linux systems.

I've updated my Arch to the same exact GCC version as yours and it still compiles, but I'll refactor that part of code anyway as it probably will fail again for someone...

**Comment by TheSunCat** [comment] 2024-02-24 22:05
Odd... thanks for taking a look! I think that would be the best option.
Looking forward to using clang-uml in my own projects.

**Closed** 2024-02-26 23:50 UTC
